liip_imagine:
#    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
#
#    # define your filter sets under this option
    filter_sets:

        instagram_thumb:
            quality : 85
            filters:
                thumbnail:
                    size: [60, 60]
                    mode: outbound

        user_small_avatar:
            quality : 85
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [30, 30]
                    mode: outbound

        user_avatar:
            quality : 85
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [160, 160]
                    mode: outbound

        user_avatar_large:
            quality : 85
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [220, 220]
                    mode: outbound

        bg_hp_region:
            quality : 85
            filters:
                auto_rotate: ~
                relative_resize:
                    widen: 625

        bg_card_item:
            quality : 85
            filters:
                downscale:
                    max: [480, 620]

        bg_card_item_without_rotate:
            quality : 85
            filters:
                auto_rotate: ~
                downscale:
                    max: [480, 620]

        bg_header_slider:
            quality : 90
            filters:
                auto_rotate: ~
                downscale:
                    max: [1920, 1200]

        card_gallery_image:
            quality : 80
            filters:
                auto_rotate: ~
                downscale:
                    max: [1920, 1200]

        card_gallery_thumb:
            quality : 85
            filters:
                auto_rotate: ~
                scale:
                    dim: [300, 200]

        pack_thumb_small:
            quality : 85
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [100, 100]
                    mode: outbound

        b2b_avatar_medium:
            quality : 85
            filters:
                auto_rotate: ~
                thumbnail:
                    size: [256, 256]
                    mode: outbound
#
#        # an example thumbnail transformation definition
#        # https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html#create-thumbnails
#        squared_thumbnail:
#
#            # set your image quality defaults
#            jpeg_quality:          85
#            png_compression_level: 8
#
#            # setup the filter steps to apply for this transformation
#            filters:
#
#                # auto rotate the image using EXIF metadata
#                auto_rotate: ~
#
#                # strip the image of all metadata
#                strip: ~
#
#                # scale and square the image to the given dimensions
#                thumbnail:
#                    size:          [253, 253]
#                    mode:          outbound
#                    allow_upscale: true
#
#                # create border by placing image on larger black background
#                background:
#                    size:     [256, 256]
#                    position: center
#                    color:    '#fff'
