knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        linkedin:
            # must be "linkedin" - it activates that type!
            type: linkedin
            # add and configure client_id and client_secret in parameters.yml
            client_id: '%env(OAUTH_LINKEDIN_CLIENT_ID)%'
            client_secret: '%env(OAUTH_LINKEDIN_CLIENT_SECRET)%'
            # a route name you'll create
            redirect_route: connect_linkedin_check
            redirect_params: {}
            use_state: false
            # Optional value to specify Linkedin's API version to use. As the time of writing, v1 is still used by default by league/oauth2-linkedin.
            # api_version: null
            # Optional value to specify fields to be requested from the profile. Since Linkedin's API upgrade from v1 to v2, fields and authorizations policy have been enforced. See https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin for more details.
            # fields: {}
            # whether to check OAuth2 "state": defaults to true
            # use_state: true
        google_client:
            type: google
            client_id: 473944240347-bgh6pirja7fcka3vo30qaoip76ueoobm.apps.googleusercontent.com
            client_secret: QOwYVIC_sGfIQuIZInMr_Yc5
            redirect_route: connect_google_action
            redirect_params: {}
            use_state: false
        facebook_client:
            # must be "facebook" - it activates that type!
            type: facebook
            # add and configure client_id and client_secret in parameters.yml
            client_id: 574827166596457
            client_secret: a305a36e9a8e5d6c4c1de679ff203da7
            # a route name you'll create
            redirect_route: connect_facebook_action
            redirect_params: {}
            graph_api_version: v4.0
            # whether to check OAuth2 "state": defaults to true
            use_state: false