kms_froala_editor:
    resource: "@KMSFroalaEditorBundle/Resources/config/routing.yml"
    prefix:   /froalaeditor
#
#front_regions_index:
#    path:/{slug}/{orderby}
#    defaults:  { _controller: App\Entity\Listener\CardProjectListener}


#----------------------------------------
# ADMIN
#----------------------------------------

controllers_admin:
    resource: ../src/Controller/Admin/
    type: annotation

#----------------------------------------
# API
#----------------------------------------

controllers_api:
              resource: ../src/Controller/Api/
              type: annotation
#----------------------------------------
# B2B
#----------------------------------------

controllers_b2b:
    resource: ../src/Controller/B2B/
    type: annotation
#----------------------------------------
# v2.0
#----------------------------------------

controllers_front_v2:
    resource: ../src/Controller/Front/V2
    type: annotation



controllers_front_homepage_v2:
    resource: ../src/Controller/Front/V2/HomepageController.php
    type: annotation
#----------------------------------------
# FRONT
#----------------------------------------
controllers_front_search:
    resource: ../src/Controller/Front/V2/SearchController.php
    type: annotation

controllers_front_homepage:
    resource: ../src/Controller/Front/Pages/HomepageController.php
    type: annotation


controllers_front_pixie:
    resource: ../src/Controller/Front/Pages/Pixie/
    type: annotation

controllers_front_user:
    resource: ../src/Controller/Front/Pages/User/
    type: annotation

controllers_front_collection:
    resource: ../src/Controller/Front/Pages/CollectionController.php
    type: annotation

controllers_front_login:
    resource: ../src/Controller/Front/Pages/LoginController.php
    type: annotation

controllers_front_pages:
    resource: ../src/Controller/Front/Pages/PagesController.php
    type: annotation

controllers_front_pixies:
    resource: ../src/Controller/Front/Pages/PixiesController.php
    type: annotation

controllers_front_old_search:
    resource: ../src/Controller/Front/Pages/SearchController.php
    type: annotation



controllers_front_users:
    resource: ../src/Controller/Front/Pages/UserController.php
    type: annotation

controllers_front_wall:
    resource: ../src/Controller/Front/Pages/WallCardsController.php
    type: annotation

controllers_front_card:
    resource: ../src/Controller/Front/Pages/CardController.php
    type: annotation

controllers_crons:
    resource: ../src/Controller/Api/MailController.php
    type: annotation

controllers_client_registration:
    resource: ../src/Controller/B2B/ClientRegistrationController.php
    type: annotation

controllers_client_login:
    resource: ../src/Controller/B2B/LoginController.php
    type: annotation

controllers_client_contact:
    resource: ../src/Controller/B2B/ContactController.php
    type: annotation

controllers_client_index:
    resource: ../src/Controller/B2B/ClientController.php
    type: annotation

controllers_community_manager_mission:
    resource: ../src/Controller/B2B/MissionController.php
    type: annotation

controllers_pack:
    resource: ../src/Controller/B2B/PackController.php
    type: annotation

controllers_front_regions:
    resource: ../src/Controller/Front/V2/RegionController.php
    type: annotation