<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Twig_Extensions_' => array($vendorDir . '/twig/extensions/lib'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Troopers\\MangopayBundle' => array($vendorDir . '/troopers/mangopay-bundle'),
    'Troopers\\AjaxBundle' => array($vendorDir . '/troopers/ajax-bundle'),
    'ProxyManager\\' => array($vendorDir . '/ocramius/proxy-manager/src'),
    'Imagine' => array($vendorDir . '/imagine/imagine/lib'),
    'Google_Service_' => array($vendorDir . '/google/apiclient-services/src'),
    'Google_' => array($vendorDir . '/google/apiclient/src'),
    'FroalaEditor' => array($vendorDir . '/froala/wysiwyg-editor-php-sdk/lib'),
    'Doctrine\\Common\\Lexer\\' => array($vendorDir . '/doctrine/lexer/lib'),
    'Behat\\Transliterator' => array($vendorDir . '/behat/transliterator/src'),
);
