<?php

declare(strict_types=1);

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    public const ROOT_PACKAGE_NAME = '__root__';
    public const VERSIONS          = array (
  'behat/transliterator' => 'v1.2.0@826ce7e9c2a6664c0d1f381cbb38b1fb80a7ee2c',
  'cocur/slugify' => 'v3.2@d41701efe58ba2df9cae029c3d21e1518cc6780e',
  'composer/ca-bundle' => '1.1.4@558f321c52faeb4828c03e7dc0cfe39a09e09a2d',
  'ddeboer/vatin' => '2.2.0@91281f32ee15eeca8c7501ed683e116865909218',
  'ddeboer/vatin-bundle' => '2.1.0@ababf94f2c6d70261dc7fe3738baf960ca7506da',
  'doctrine/annotations' => 'v1.6.1@53120e0eb10355388d6ccbe462f1fea34ddadb24',
  'doctrine/cache' => 'v1.8.0@d768d58baee9a4862ca783840eca1b9add7a7f57',
  'doctrine/collections' => 'v1.6.1@d2ae4ef05e25197343b6a39bae1d3c427a2f6956',
  'doctrine/common' => 'v2.10.0@30e33f60f64deec87df728c02b107f82cdafad9d',
  'doctrine/dbal' => 'v2.9.2@22800bd651c1d8d2a9719e2a3dc46d5108ebfcc9',
  'doctrine/doctrine-bundle' => '1.11.1@09a38417339dc93849d051b914aae3947eb231a7',
  'doctrine/doctrine-cache-bundle' => '1.3.5@5514c90d9fb595e1095e6d66ebb98ce9ef049927',
  'doctrine/doctrine-migrations-bundle' => 'v2.0.0@4c9579e0e43df1fb3f0ca29b9c20871c824fac71',
  'doctrine/event-manager' => 'v1.0.0@a520bc093a0170feeb6b14e9d83f3a14452e64b3',
  'doctrine/inflector' => 'v1.3.0@5527a48b7313d15261292c149e55e26eae771b0a',
  'doctrine/instantiator' => '1.2.0@a2c590166b2133a4633738648b6b064edae0814a',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v2.0.2@43280c14b696a7896a9c70a5e0e4a312ff003187',
  'doctrine/orm' => 'v2.6.3@434820973cadf2da2d66e7184be370084cc32ca8',
  'doctrine/persistence' => '1.1.1@3da7c9d125591ca83944f477e65ed3d7b4617c48',
  'doctrine/reflection' => 'v1.0.0@02538d3f95e88eb397a5f86274deb2c6175c2ab6',
  'easycorp/easy-log-handler' => 'v1.0.7@5f95717248d20684f88cfb878d8bf3d78aadcbba',
  'egulias/email-validator' => '2.1.8@c26463ff9241f27907112fbcd0c86fa670cfef98',
  'fig/link-util' => '1.0.0@1a07821801a148be4add11ab0603e4af55a72fac',
  'firebase/php-jwt' => 'v5.0.0@9984a4d3a32ae7673d6971ea00bae9d0a1abba0e',
  'froala/wysiwyg-editor-php-sdk' => '1.1.0@97fd241a19d467268e6eda816c1d9a4dffb5ad97',
  'gedmo/doctrine-extensions' => 'v2.4.37@5dd471f656e46d815f063bf3f12c667649ec7ffb',
  'google/apiclient' => 'v2.2.3@4bfd3edc21cceaf45fc216a4196e1993cf7a89eb',
  'google/apiclient-services' => 'v0.101@be4d5cb91965dd03e47f88186b5ae95a21050ce7',
  'google/auth' => 'v1.5.1@0f75e20e7392e863f5550ed2c2d3d50af21710fb',
  'guzzlehttp/guzzle' => '6.3.3@407b0cb880ace85c9b63c5f9551db498cb2d50ba',
  'guzzlehttp/promises' => 'v1.3.1@a59da6cf61d80060647ff4d3eb2c03a2bc694646',
  'guzzlehttp/psr7' => '1.5.2@9f83dded91781a01c63574e387eaa769be769115',
  'imagine/imagine' => 'v0.7.1@a9a702a946073cbca166718f1b02a1e72d742daa',
  'jdorn/sql-formatter' => 'v1.2.17@64990d96e0959dff8e059dfcdc1af130728d92bc',
  'kms/froala-editor-bundle' => 'v2.9.4@a51f2328d6eb4f4ed9f768465798fe8403eb4929',
  'knplabs/knp-snappy' => 'v1.1.0@ea037298d3c613454da77ecb9588cf0397d695e1',
  'knplabs/knp-snappy-bundle' => 'v1.6.0@87acf8544a2bd498585b3d49b2bb551f088551b1',
  'knpuniversity/oauth2-client-bundle' => 'v1.28.0@f0f10560f6a8806cf6f3811f5fb53221aa3c7145',
  'league/oauth2-client' => '2.4.1@cc114abc622a53af969e8664722e84ca36257530',
  'league/oauth2-facebook' => '2.0.1@bcbcd540fb66ae16b4f82671c8ae7752b6a89556',
  'league/oauth2-google' => '2.2.0@c0faed29ec6d665ce3234e01f62029516cee4c02',
  'liip/imagine-bundle' => '2.1.0@1acae6ac066e431c3c55c4d39971827a02cbe4d5',
  'mangopay/php-sdk-v2' => '2.12.0@7aa78de5e0393a91ffdb380f84cc1145d0f87c48',
  'monolog/monolog' => '1.24.0@bfc9ebb28f97e7a24c45bdc3f0ff482e47bb0266',
  'nikic/php-parser' => 'v4.2.2@1bd73cc04c3843ad8d6b0bfc0956026a151fc420',
  'ocramius/package-versions' => '1.4.0@a4d4b60d0e60da2487bd21a2c6ac089f85570dbb',
  'ocramius/proxy-manager' => '2.2.2@14b137b06b0f911944132df9d51e445a35920ab1',
  'paragonie/random_compat' => 'v9.99.99@84b4dfb120c6f9b4ff7b3685f9b8f1aa365a0c95',
  'phpdocumentor/reflection-common' => '1.0.1@21bdeb5f65d7ebf9f43b1b25d404f87deab5bfb6',
  'phpdocumentor/reflection-docblock' => '4.3.1@bdd9f737ebc2a01c06ea7ff4308ec6697db9b53c',
  'phpdocumentor/type-resolver' => '0.4.0@9c977708995954784726e25d0cd1dddf4e65b0f7',
  'phpseclib/phpseclib' => '2.0.17@3ca5b88d582c69178c8d01fd9d02b94e15042bb8',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.0.0@b7ce3b176482dbbc1245ebf52b181af44c2cf55f',
  'psr/http-message' => '1.0.1@f6561bf28d520154e4b0ec72be95418abe6d9363',
  'psr/link' => '1.0.0@eea8e8662d5cd3ae4517c9b864493f59fca95562',
  'psr/log' => '1.1.0@6c001f1daafa3a3ac1d8ff69ee4db8e799a654dd',
  'ralouphie/getallheaders' => '2.0.5@5601c8a83fbba7ef674a7369456d12f1e0d0eafa',
  'sensio/framework-extra-bundle' => 'v5.3.1@5f75c4658b03301cba17baa15a840b57b72b4262',
  'sensiolabs/security-checker' => 'v5.0.3@46be3f58adac13084497961e10eed9a7fb4d44d1',
  'stof/doctrine-extensions-bundle' => 'v1.3.0@46db71ec7ffee9122eca3cdddd4ef8d84bae269c',
  'sverraest/revolut-php' => 'v1.1.1@dc56421a284eb1ce2b6a581fd81e631bc0fc428a',
  'sverraest/revolut-php-bundle' => 'v1.0.1@8cc5621efd6f8b3b3b92e2dd7bf9bdc7fa40fc62',
  'swiftmailer/swiftmailer' => 'v6.2.1@5397cd05b0a0f7937c47b0adcb4c60e5ab936b6a',
  'symfony/apache-pack' => 'v1.0.1@3aa5818d73ad2551281fc58a75afd9ca82622e6c',
  'symfony/asset' => 'v4.3.0@5cc4a0cf86cbaeb3dc5bf3d875261169141574c9',
  'symfony/cache' => 'v4.3.0@f09463d1165396745fef0aae64b7a784c891be9f',
  'symfony/cache-contracts' => 'v1.1.1@7ff3902cc747dd5e2c6f26dc42603ed07b530293',
  'symfony/config' => 'v4.3.0@5455fc0ae8b46269b83a22949429ea878496408c',
  'symfony/console' => 'v4.3.0@707b619d2c3bedf0224d56f95f77dabc60102305',
  'symfony/debug' => 'v4.3.0@97cde06d798f1326857090bc1b7c8f9d225c3dcb',
  'symfony/debug-bundle' => 'v4.3.0@9b80d1c97c11950f3e49c12fef3c8ccc8a42e601',
  'symfony/debug-pack' => 'v1.0.7@09a4a1e9bf2465987d4f79db0ad6c11cc632bc79',
  'symfony/dependency-injection' => 'v4.3.0@aa6fe799fa5adc938fc55aeccd2f5fb0aa0b8eac',
  'symfony/doctrine-bridge' => 'v4.3.0@5803336d65b4c7de8185d8947e843810ec61012d',
  'symfony/event-dispatcher' => 'v4.3.0@c71314cd3b9420b732e1526f33a24eff5430b5b3',
  'symfony/event-dispatcher-contracts' => 'v1.1.1@8fa2cf2177083dd59cf8e44ea4b6541764fbda69',
  'symfony/expression-language' => 'v4.3.0@94f1b244c3f2f5e6d360d3d63d3ef77a5fc8aa82',
  'symfony/filesystem' => 'v4.3.0@988ab7d70c267c34efa85772ca20de3fad11c74b',
  'symfony/finder' => 'v4.3.0@b3d4f4c0e4eadfdd8b296af9ca637cfbf51d8176',
  'symfony/flex' => 'v1.2.5@27909122a3da4676c3dc5dc34c8f82323c610d69',
  'symfony/form' => 'v4.3.0@f2473c6a91b6d77b6c293b09ce2ebb079f4c8f21',
  'symfony/framework-bundle' => 'v4.3.0@19714b45c7b5af238e66720017bae6fcf2d5fa01',
  'symfony/http-foundation' => 'v4.3.0@e8da078912bed1339f046c3a9488a5cbd0605971',
  'symfony/http-kernel' => 'v4.3.0@b4ce396bdce518978a17324d3d39d61058d039e6',
  'symfony/inflector' => 'v4.3.0@fc31c163077e75bb0b1055fe60a27f5c3cb9ae7c',
  'symfony/intl' => 'v4.3.0@98e7de6ec772cdb6085abf947cb08953cb24f441',
  'symfony/lts' => 'dev-master@c1affae45b78aee036effa1759237e7fa96d4af2',
  'symfony/maker-bundle' => 'v1.11.6@d262c2cace4d9bca99137a84f6fc6ba909a17e02',
  'symfony/mime' => 'v4.3.0@0b166aee243364cd9de05755d2e9651876090abb',
  'symfony/monolog-bridge' => 'v4.3.0@8365f0e5fed85841f977cf9d665bfb61b392dcdf',
  'symfony/monolog-bundle' => 'v3.3.1@572e143afc03419a75ab002c80a2fd99299195ff',
  'symfony/options-resolver' => 'v4.3.0@914e0edcb7cd0c9f494bc023b1d47534f4542332',
  'symfony/orm-pack' => 'v1.0.6@36c2a928482dc5f05c5c1c1b947242ae03ff1335',
  'symfony/polyfill-ctype' => 'v1.11.0@82ebae02209c21113908c229e9883c419720738a',
  'symfony/polyfill-intl-icu' => 'v1.11.0@999878a3a09d73cae157b0cf89bb6fb2cc073057',
  'symfony/polyfill-intl-idn' => 'v1.11.0@c766e95bec706cdd89903b1eda8afab7d7a6b7af',
  'symfony/polyfill-mbstring' => 'v1.11.0@fe5e94c604826c35a32fa832f35bd036b6799609',
  'symfony/polyfill-php72' => 'v1.11.0@ab50dcf166d5f577978419edd37aa2bb8eabce0c',
  'symfony/polyfill-php73' => 'v1.11.0@d1fb4abcc0c47be136208ad9d68bf59f1ee17abd',
  'symfony/process' => 'v4.3.0@a5e3dd4e93a364668034a3cb6efa963d0b33ab45',
  'symfony/profiler-pack' => 'v1.0.4@99c4370632c2a59bb0444852f92140074ef02209',
  'symfony/property-access' => 'v4.3.0@a14764290356f3fd17b65d2e98babc19b85e2814',
  'symfony/property-info' => 'v4.3.0@9a3d5ba14694017a29cada773ce770845224d9e4',
  'symfony/routing' => 'v4.3.0@e6cc85f03102ef5e4aedfe636f83e58cf6fd7338',
  'symfony/security-bundle' => 'v4.3.0@cb5ea7c36f0ee17ddd003dc3477d626281731115',
  'symfony/security-core' => 'v4.3.0@b69e4898a4a2f950e24672836c9ecd40ca4883bb',
  'symfony/security-csrf' => 'v4.3.0@2ec1a4047302de6d0c4fb2cc377e578f530097c7',
  'symfony/security-guard' => 'v4.3.0@33621882e935a2b7fa558311ffe9a4f6b1b7ee9f',
  'symfony/security-http' => 'v4.3.0@13594beb3faaeea891aaae9eeea8ffde16a99faf',
  'symfony/serializer' => 'v4.3.0@4bb37f32833c7fc72a6b2dc2abf545918c77fb6e',
  'symfony/serializer-pack' => 'v1.0.2@c5f18ba4ff989a42d7d140b7f85406e77cd8c4b2',
  'symfony/service-contracts' => 'v1.1.2@191afdcb5804db960d26d8566b7e9a2843cab3a0',
  'symfony/stopwatch' => 'v4.3.0@6b100e9309e8979cf1978ac1778eb155c1f7d93b',
  'symfony/swiftmailer-bundle' => 'v3.2.7@959459318a022f9ad6bc85e3a87a0a10af173ff1',
  'symfony/templating' => 'v4.3.0@70da2d83b16e7b717b3e02debacaf66da8c07ef4',
  'symfony/translation' => 'v4.3.0@f7e90f0f90e354f99f20aa9ead95a1b201b126f9',
  'symfony/translation-contracts' => 'v1.1.2@93597ce975d91c52ebfaca1253343cd9ccb7916d',
  'symfony/twig-bridge' => 'v4.3.0@5ed4b37b36e37baeb36028e2e27725c571853444',
  'symfony/twig-bundle' => 'v4.3.0@2792936cbcd92267596363b67b5cebb5e347af59',
  'symfony/validator' => 'v4.3.0@6ad0600c5a4bb673a627533f88b77b2af43e71b7',
  'symfony/var-dumper' => 'v4.3.0@2fd2ecf7913fb96f0c2e941ca15bb702184c6574',
  'symfony/var-exporter' => 'v4.3.0@2b7c857d553423b2317ac0741fb2581d9bfd8fb7',
  'symfony/web-link' => 'v4.3.0@af0e386322f192ed50bd9c812daedce05368733c',
  'symfony/web-profiler-bundle' => 'v4.3.0@b371e362dada3c1fcd9e7f7a31a91bd681860331',
  'symfony/webpack-encore-pack' => 'v1.0.3@8d7f51379d7ae17aea7cf501d910a11896895ac4',
  'symfony/yaml' => 'v4.3.0@c60ecf5ba842324433b46f58dc7afc4487dbab99',
  'troopers/ajax-bundle' => '1.3.2@7b4520f202f7dd7c32b737ab96d070f332617fd1',
  'troopers/mangopay-bundle' => '3.0.5@56c0061a650bf1a96a16a796deca242cd4acfbdb',
  'twig/extensions' => 'v1.5.4@57873c8b0c1be51caa47df2cdb824490beb16202',
  'twig/twig' => 'v2.11.0@c344879ae57dc1487b1df3e3d8325936125ba2cc',
  'webmozart/assert' => '1.4.0@83e253c8e0be5b0257b881e1827274667c5c17a9',
  'zendframework/zend-code' => '3.3.1@c21db169075c6ec4b342149f446e7b7b724f95eb',
  'zendframework/zend-eventmanager' => '3.2.1@a5e2583a211f73604691586b8406ff7296a946dd',
  'symfony/browser-kit' => 'v4.3.0@3fa7d8cbd2e5006038a09b8ef93f3859a89b627e',
  'symfony/css-selector' => 'v4.3.0@105c98bb0c5d8635bea056135304bd8edcc42b4d',
  'symfony/dom-crawler' => 'v4.3.0@28edb1d371640654fbfb9df53d70fa03fdf69fb6',
  'symfony/dotenv' => 'v4.3.0@efd677abff68ea6fcfd9c60dbdacb96d0d97b382',
  'symfony/phpunit-bridge' => 'v4.3.0@7bfc1b57d1ac9513703391498aa8da4764388bc6',
  'symfony/web-server-bundle' => 'v4.3.0@a5391b6a4ac78d518dd3f0ee5f40bcc9a7ee6fe7',
  'symfony/polyfill-iconv' => '*@7592be441e86d1e497ada5687556122a51c36b04',
  'symfony/polyfill-php71' => '*@7592be441e86d1e497ada5687556122a51c36b04',
  'symfony/polyfill-php70' => '*@7592be441e86d1e497ada5687556122a51c36b04',
  'symfony/polyfill-php56' => '*@7592be441e86d1e497ada5687556122a51c36b04',
  '__root__' => 'dev-master@7592be441e86d1e497ada5687556122a51c36b04',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException If a version cannot be located.
     */
    public static function getVersion(string $packageName) : string
    {
        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new \OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: cannot detect its version'
        );
    }
}
